name: ConquestPlugin
version: ${project.version}
main: com.tempustpvp.conquests.conquestplugin.ConquestPlugin
depend: [Factions, WorldGuard, MassiveCore, PlaceholderAPI, ProtocolLib]
authors: [Sunny]
description: Conquest plugin
